### PR TITLE
Upgrade to net standard 2.0 and net461

### PR DESCRIPTION
**Pull request by Alegrowin**
### Description

Write a few lines what about the pull request, don't forget to include ticket refereneces to issues it solves.

### Check List

- [ ] All test passed.
- [ ] Added documentation _(if applicable)_.
- [ ] Tests added to ensure functionality.
- [ ] Pull Request to `stable` branch.

### CODE REVIEW

**Comment by pardahlman** [comment]
Hi @Alegrowin - can you write a few lines about why this is a good idea? Thanks!

**Comment by tristan-hyams** [comment]
The performance gains and bug fixes alone in the two updates would be worth it. Including security fixes.

.NET 4.5.1 is EoL and shouldn't have been the target for a new project. 4.6.x family introduced us to Ryujit performance wise.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by Alegrowin** [comment]
I will update this PR, thanks @thyams

**Comment by Alegrowin** [comment]
See https://github.com/pardahlman/RawRabbit/pull/357

@thyams I've been reading about the TargetFramework and there is no difference in the generated assemblies between a .net451 and .net4x code. In the newest version of the .Net Framework there is extra features which can be used when developing. But the generated code is the exact same byte size when using .net451 and 472 for example. The real big difference is the version of the dll used when compiling and the CLR used to execute the dll's. For those reasons, I will not enforce the 46x version of the framework as some consummer of this library may not be ready to use .net46x.

**Comment by tristan-hyams** [comment]
I may do a PR to add netstandard 2.0 and 461 as additional targets.

Instead of forcing users to update, it will allow the user to choose.

The performance benefits are there in clr versions and RyuJit.

**Comment by tristan-hyams** [comment]
461 is out. Task completion source has an async bug in 461.

RawRabbits Invoke and Execution lock is dependent on this for
PublishConfirmTimout Exceptions.

https://support.microsoft.com/en-us/help/3118695/runcontinuationsasynchronously-does-not-run-continuations-asynchronous

**Comment by Alegrowin** [comment]
@thyams I have provided the support for .netstandard2.0 in  https://github.com/pardahlman/RawRabbit/pull/357. Maybe you could take a look at it.

**Pull request closed without merging**
